#!/bin/bash

# Compile
# shellcheck disable=SC2164
pushd "zakkhoyt"
mkdocs build

# Serve (in background)
mkdocs serve &


# Sleep before opening server
sleep 2

hatch_log -d "Serving locally. To view: open http://127.0.0.1:8000" 
echo_pretty "Serving locally. To view: " --yellow --bold "open http://127.0.0.1:8000" --default
open http://127.0.0.1:8000

popd